package Lexico;

public enum Tipos {
    OPSOMA, OPSUB, OPMUL, OPDIV, OPIGUAL, OPMAIOR, OPMENOR,
    OPMAIORIGUAL, OPMENORIGUAL, OPNEG, OPDIFE,

    COND_AND, COND_OR,

    AP, FP, AC, FC, PV,

    NUM_INT, NUM_REAL,

    INTEGER, DOUBLE, STRING, BOOLEAN, VL_TRUE, VL_FALSE,

    TXTSTRING,

    FUN_IF, FUN_ELSE, FUN_FOR, FUN_WHILE, FUN_PRINT,

    DEF_CLASS, DEF_FUNCTION,

    BREAK,

    LINE_BREAK,

    ID,

    ERROR
}
