package Lexico;

public enum Tipos {
    OPSOMA, OPSUB, OPMUL, OPDIV, OPIGUAL, OPMAIOR, OPMENOR,
    OPMAIORIGUAL, OPMENORIGUAL, OPNEG, OPDIFE,

    COND_AND, COND_OR,

    AP, FP,

    NUM_INT, NUM_REAL,

    INTEGER, DOUBLE, STRING, BOOLEAN,

    ID
}
